### ISSUE TITLE
Keyjar Overridden when using JWKS config

### ISSUE THREAD

**Issue by heyden** [IdentityPython/JWTConnect-Python-OidcRP#14]
When using the JWKS setup via client configuration it appears the keyjar that is required as input will override the keyjar initialized with the JWKS keys.

[Reference](https://github.com/openid/JWTConnect-Python-OidcRP/blob/master/src/oidcrp/__init__.py#L204)

Through some debugging, I can see the JWKS keys loaded from the remote endpoint, however it's overriden by the keyjar provided to RPhandler. A keyjar must be provided due to the above line as well.

Sample code:

```python
options = {
  "myidp": {
    # ...
     keys { url: { 'myissuer': 'IDP JWKS endpoint' } }
  }
}
```

**Comment by peppelinux** [comment]
Hi @heyden long time passed but we still interested in this.
Can you do a test with the latest jwtconnect master branches and then report the result here?
We'll wait for another week for this othewise we'll close this issue.
Hope in feedback

**Comment by heyden** [comment]
@peppelinux I can certainly do that and will report back once I test.

I was able to work around this issue by setting the keyjar after the RPHandler initialization.

**Comment by peppelinux** [comment]
That's not here:
https://github.com/peppelinux/django-oidc-op/blob/master/snippets/rp_handler.py

Take a look and dig together

**Comment by heyden** [comment]
It looks like there have been many additions since I last looked at this and it could very well be resolved. After investigating [src/oidcrp/init.py#L175-L182](https://github.com/IdentityPython/JWTConnect-Python-OidcRP/blob/master/src/oidcrp/__init__.py#L175-L182) it does appear to do some additional checks and have better handling. I will look to test this out early next week assuming that there has not been any drastic API changes, I should be able to confirm fairly quickly.

To articulate what I originally ran into, I went back to the commit in question and it was this line [src/oidrpc/init.py#204](https://github.com/IdentityPython/JWTConnect-Python-OidcRP/blob/2e2f07502237113455272d84407d615f19aafd1e/src/oidcrp/__init__.py#L204) that conflicted with any loaded JWKS if the issuer JWKS endpoint was provided in the `client_configs` as detailed in the original post.

Right before this line it instantiates the client which loads the JWKS from the remote endpoint from what I remember.

This is how I worked around the problem at the time but normally you would not do this as the library is capable of loading the JWKS from a remote source.

```python
from cryptojwt.key_bundle import KeyBundle
from crpytojwt.key_jar import KeyJar
from oidcrp import RPHandler

jwks_endpoint = 'omitted...issuer endpoint...'

keyjar = Keyjar()
kb = KeyBundle(verify_ssl=True, source=jwks_endpoint )
keyjar.add_kb('myissuer', kb)

client_configs = {
  'idp': {
    'issuer': 'myissuer',
    'client_id': 'myclientid',
    'client_secret': 'myclientsecret',
    'behavior': {
      # ...omitted
    },
    provider_info': {
      # ...omitted
    },
    # ... rest omitted
  }
}

# workaround by loading the JWKS ourselves and passing in the configured keyjar
# otherwise, expected to work like so
# rph = RPHandler(client_configs=client_configs, verify_ssl=True)
rph = RPHandler(client_configs=client_configs, keyjar=keyjar, verify_ssl=True)
```
