### ISSUE TITLE
AttributeError following the documentation

### ISSUE THREAD

**Issue by jorgii** [IdentityPython/JWTConnect-Python-OidcRP#24]
Hello,

I was following the [documentation](https://oidcrp.readthedocs.io/en/latest/rp_handler.html#tier-1-api) and I got an exception on the second command.
```
In [7]: rph = RPHandler()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-4a3a68ab1524> in <module>
----> 1 rph = RPHandler()

~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in __init__(self, base_url, hash_seed, keyjar, verify_ssl, services, client_configs, client_authn_factory, client_cls, state_db, http_lib, httpc_params, **kwargs)
    152             self.httpc_params = httpc_params
    153
--> 154         if not self.keyjar.httpc_params:
    155             self.keyjar.httpc_params = self.httpc_params
    156

AttributeError: 'NoneType' object has no attribute 'httpc_params'
```

It looks like some `keyjar` parameter blows and there is no mention of it in the documentation but according to the __init__ method definition the `keyjar` parameter is optional.

Am I doing something wrong or is this simply a bug?

**Comment by rohe** [comment]
`keyjar` isn't really optional. The same goes for `base_url` and `hash_seed`.
Should change that.
Thanks for pointing it out.

**Comment by jorgii** [comment]
There seems to be more things mandatory. I tried to add the properties you added:
```python
rph = RPHandler(verify_ssl=False, keyjar=KeyJar(), base_url='http://localhost:8081', hash_seed='foo')
```
and on the next step I get another exception:
```
In [14]: info = rph.begin(issuer_id)
[2020-03-17 10:44:46,554] INFO    : client_setup: iss_id=http://localhost:8081/auth/realms/mgt_ecosystem, user=
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in client_setup(self, iss_id, user)
    340         try:
--> 341             client = self.issuer2rp[iss_id]
    342         except KeyError:

KeyError: 'http://localhost:8081/auth/realms/mgt_ecosystem'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-14-8ce031b349b0> in <module>
----> 1 info = rph.begin(issuer_id)

~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in begin(self, issuer_id, user_id)
    463
    464         # Get the client instance that has been assigned to this issuer
--> 465         client = self.client_setup(issuer_id, user_id)
    466
    467         try:

~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in client_setup(self, iss_id, user)
    345             else:
    346                 logger.debug("Creating new client: %s", iss_id)
--> 347                 client = self.init_client(iss_id)
    348         else:
    349             return client

~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in init_client(self, issuer)
    195         :return: A Client instance
    196         """
--> 197         _cnf = self.pick_config(issuer)
    198         try:
    199             _services = _cnf['services']

~/.virtualenvs/connect_api/lib/python3.7/site-packages/oidcrp/__init__.py in pick_config(self, issuer)
    174         :return: A client configuration
    175         """
--> 176         return self.client_configs[issuer]
    177
    178     def get_session_information(self, key):

TypeError: 'NoneType' object is not subscriptable
```

Btw, my oidc provider is Keycloak.

Is there anywhere a proper tutorial I can follow for this library (to avoid wasting your time)?

**Comment by rohe** [comment]
Yeah, looking at it right now :-)
Basically trying to find out if there are useful defaults.

**Comment by rohe** [comment]
OK, turns out that the only thing that is not optional is base_url.
The rest I can find reasonable defaults for.
Have to verify I haven't broken anything with this work. 
If I haven't I'll upload the changes to GitHub later today.

**Comment by rohe** [comment]
There is no proper tutorial. Would be nice to have :-/
Hmm, Keycloak .. I haven't tried to connect to them.
I guess then only support static configuration, right ?

**Comment by jorgii** [comment]
Hm, not sure about the config, I am not that into the protocol :(

**Comment by rohe** [comment]
I have not read the whole documentation (just quickly browsed through) but this section tells me it only does static client registration:
https://www.keycloak.org/docs/4.8/server_admin/#oidc-clients

Do you (or someone in your vicinity) have a Keycloak server running ?

**Comment by jorgii** [comment]
You should be able to spawn one easily using docker - https://hub.docker.com/r/jboss/keycloak/
`docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin jboss/keycloak`

**Comment by rohe** [comment]
Sorry, don't have the time the next couple of weeks.

**Comment by peppelinux** [comment]
Hi @jorgii let's see together how to handle this.
Have you produced a patch or do you have any updates for this?

**Comment by jorgii** [comment]
> Hi @jorgii let's see together how to handle this.
> Have you produced a patch or do you have any updates for this?

I have no update here. Unfortunately I am not familiar with OIDC that much to be able to produce a patch. I simply reported an unusual behaviour I noticed while going through the docs.

Do you think there is a way I can help?

**Comment by peppelinux** [comment]
Yes, just put a public running instance, I'll try to connect an example RP to see what's happens.
Sorry if I didn't deployed a keycloak docker instance yet, there are many things these days, hope you'll understand.

If you can help us this way, that would be great

**Comment by rohe** [comment]
We're working on updating the docs and the example.
