### ISSUE TITLE
Concurrent sessions: Key error on get_session_information

### ISSUE THREAD

**Issue by ddiosono** [IdentityPython/JWTConnect-Python-OidcRP#28]
Hello,
In a project I use the library oidcrp ver 0.6.3.
During the tests an exception is raised in case of concurrent sessions. 

This is the test case:

```
rph.begin (1st user), state1 is saved
rph.begin (2nd user), state2 is saved
rph.get_session_information(state1) -> Key error is raised
```

The KeyError exception is raised because the state is not found in state db (state value is correct and state_db implemented as InMemoryStateDataBase).

Do you have any hint to share?

Thanks in advance

Regards,
Davide

**Comment by peppelinux** [comment]
Not at this moment but I should investigate in the storage folder and put some debugging actions in oidcendpoint.sso_db (get and set method). We should check if a concurrent session, in the actuale storage paradigm, would overwrite the older.

Please let us know about this, I'll follow you as many as possibile

**Comment by ddiosono** [comment]
To clarify the situation by concurrent sessions I mean two different users that initiate the authorization process.
What I observe is that the pointer of the RPHandler object (rph) defined as global changes.
As consequence the state cannot be found in state_db.

**Comment by rohe** [comment]
So, why do you initiate 2 RPHandlers ? Because that is the only reason why it would change.
Since each RPHandler keeps their own session database, not finding that state value stored by the other instance is what one would expect.
You have to go back to your application and look at where you initiated the RPhandler. 
You should only have one.

**Comment by peppelinux** [comment]
@ddiosono which kind of application are you using, a framework like flask or django?
If django I would be interested to partecipate.

Standing on what Roland told us the RPHandler would be initialized once, in __init__.py. ITs objects would be also importable in your views

**Comment by neoflex** [comment]
If you are using something like gunicorn with multiple workers, multiple python processes will be spawned and they cannot share the same objects in memory. As a result, it is not possible to use the InMemoryStateDataBase state_db. I am currently facing the same issue. A solution could be to use something like redis to share the states between different processes. The RPHandler constructor takes as parameter a state_db implementation. We would need a RedStateDatabase implementation.

**Comment by davidkhess** [comment]
It looks like there is an implementation of state_db that can use SQLAlchemy implemented here:

https://github.com/IdentityPython/JWTConnect-Python-OidcMsg/blob/master/src/oidcmsg/storage/absqlalchemy.py

Does anybody have a recipe for getting this configured and working?

**Comment by peppelinux** [comment]
It's obsolete, It should be refactored and tested. I continue working in django-oidc-op, if anyone wouldn't put a contribute on sqlalchemy storage well, we would remove It from the project

**Comment by davidkhess** [comment]
I got AbstractStorageSQLAlchemy working and will clean it up into a PR.

**Comment by peppelinux** [comment]
> I got AbstractStorageSQLAlchemy working and will clean it up into a PR.

Is there any additional commti that you would do in AbstractStorageSQLAlchemy?
Fill free to do that

**Comment by davidkhess** [comment]
Yes, it needs updates. Also, the way it handles the table setup is awkward so I'm going to change that.

**Comment by davidkhess** [comment]
Two pull requests related to this issue:

https://github.com/IdentityPython/JWTConnect-Python-OidcMsg/pull/20
https://github.com/IdentityPython/JWTConnect-Python-OidcRP/pull/32

With those two, I was able to get persistent storage into an Postgres table working.

Thanks for these libraries!

**Comment by rohe** [comment]
We've rewritten the persistent storage system.
The actual storage is now outside the package suppost to be done by whatever frontend you're using.
The package provides dump/load/flush methods that can be used to get the information that should be stored and to update a running instance with stored information.

**Comment by peppelinux** [comment]
We need documentation on oidc-rp for load/dump/flush
