### ISSUE TITLE
Default logging configuration behavior is too aggressive

### ISSUE THREAD

**Issue by davidkhess** [IdentityPython/JWTConnect-Python-OidcRP#31]
The `Configuration` class calls `configure_logging` which assumes under all conditions that it is responsible for configuring the logging module via a call to `logging.dictConfig`.

This seems odd for a library to assume this especially when integrated into larger applications where logging configuration and setup is under control of the application.

I'd recommend a change that if no logging configuration is indicated, then no logging configuration should be attempted. Instead, just return `getLogger("oidcrp")` and work with whatever configuration has been set in the runtime environment by other code.

**Comment by davidkhess** [comment]
Here's a monkey patch to work around it:

```
def install_monkey_patch():
    import logging
    import oidcrp.logging
    import oidcrp.configure

    def configure_logging(debug=False, config=None, filename=None):
        return logging.getLogger("oidcrp")

    oidcrp.logging.configure_logging = configure_logging
    oidcrp.configure.configure_logging = configure_logging
```

**Comment by rohe** [comment]
Sounds reasonable.

**Comment by rohe** [comment]
Done
