### ISSUE TITLE
Test application throws error "argument after ** must be a mapping"

### ISSUE THREAD

**Issue by tomasbrchan** [IdentityPython/JWTConnect-Python-OidcRP#59]
Hi.
New version of oidcrp does this:
```
Traceback (most recent call last):
  File "JWTConnect-Python-OidcRP\example\flask_rp\wsgi.py", line 28, in <module>
    app = application.oidc_provider_init_app(_config.rp, name, template_folder=template_dir)
  File "JWTConnect-Python-OidcRP\example\flask_rp\application.py", line 52, in oidc_provider_init_app
    app.rph = init_oidc_rp_handler(app)
  File "JWTConnect-Python-OidcRP\example\flask_rp\application.py", line 17, in init_oidc_rp_handler
    _kj = init_key_jar(**_rp_conf.keys)
TypeError: cryptojwt.key_jar.init_key_jar() argument after ** must be a mapping, not builtin_function_or_method
```
I am not sure where is the problem, I just found it after updating all packages by pip and found that this is something I am not able to solve.
Can somebody look at this or give me a solution?
Thank a lot, Tomas.

**Comment by tomasbrchan** [comment]
Thank you very much. It helped. I also changed it in my project and it works.

Just a note: The line 16: "if _rp_conf.keys:" is ok?

**Comment by rohe** [comment]
Excellent !

And you're right. line 16 should also change.

**Comment by tomasbrchan** [comment]
OK, I will change it then in my project also.
I am closing the issue than.
